<?php

namespace WP\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * DirectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDirectorWithMovieId($id) {
        $qb = $this
                ->createQueryBuilder('d');
        
        $qb
                ->leftJoin('d.movies','m')
                ->where($qb->expr()->in('m.id',$id))
                ->addSelect('m');
        
        return $qb
                ->getQuery()
                ->getResult();
    }
    
    public function getRecentDirectors($page, $nbPerPage) {
        $query = $this->createQueryBuilder('d')
                ->leftJoin('d.image', 'i')
                ->addSelect('i')
                ->leftJoin('d.movies', 'm')
                ->addSelect('m')
                ->orderBy('d.id', 'DESC')
                ->getQuery();

        $query->setFirstResult(($page - 1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
