<?php

namespace WP\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ViewlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewlistRepository extends \Doctrine\ORM\EntityRepository {

    public function getHistory($user, $page, $nbPerPage) {
        $query = $this->createQueryBuilder('v')
                ->leftJoin('v.movie', 'm')
                ->addSelect('m')
                ->leftJoin('v.user', 'u')
                ->addSelect('u')
                ->where('v.view = 1')
                ->andWhere('u.id = :user')
                ->setParameter('user', $user)
                ->orderBy('v.id', 'DESC')
                ->getQuery();

        $query->setFirstResult(($page - 1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

}
