<?php

namespace WP\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getWishlist($user, $page, $nbPerPage) {
        $query = $this->createQueryBuilder('w')
                ->leftJoin('w.movie', 'm')
                ->addSelect('w')
                ->leftJoin('w.user', 'u')
                ->addSelect('u')
                ->where('w.wish = 1')
                ->andWhere('u.id = :user')
                ->setParameter('user', $user)
                ->orderBy('w.id', 'DESC')
                ->getQuery();

        $query->setFirstResult(($page - 1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
